import Navbar from "@/components/Navbar";
import "./globals.css";
import { NextAuthProvider } from "./Providers";
import UserInfo from "@/components/UserInfo";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body>
          <div className="max-w-3xl mx-auto p-4">
            <Navbar />
            <UserInfo />
            <div className="mt-8"> {children}</div>
          </div>
        </body>
      </NextAuthProvider>
    </html>
  );
}
